#! /usr/bin/perl

my $FLAGS = "-lSDL -lGL -lGLU";
my $LIBS  = "-g -Wall";

sub shared {
	my $C_FILES = `find . -regex \".*.cpp\" -printf "%p "`;
	system("clear");
	my $command = "g++ $C_FILES $FLAGS $LIBS -o GSC.so -shared\n";
	print $command and system($command);
}

sub static {
	my @C_FILES = `find . -regex ".*.cpp"`;
	system("clear");
	foreach (@C_FILES) {
		chop;
		m/.*\/(.*)\.cpp/;
		my $name = $1;

		my $command = "g++ $_ $FLAGS $LIBS -o bin/$name.o -c\n";
		print $command and system($command);
	}

	print "\nLinking . . .\n\n";
	my $command = "ar rc libGSC.a bin/*.o\n";
	print $command and system($command);
}

while ((my $arg = shift(@ARGV))) {
	if ($arg =~ "shared")      { shared; }
	elsif ($arg =~ "static") { static; }
	else { print 
		"Usage: $0 <BUILD-TYPE>\nBUILD TYPES:\n\tshared - compile GSC into a shared library for dynamic runtime linking.
		\tstatic - compile GSC into a static library for compilation linking.\n" and exit; }
}
